base: https://buildawesome.one
title: 11ty / Build Awesome One
brand: '<big class="mark-brand" style="display: inline-block"><i class="fa-brands fa-build-awesome fa-width-auto"></i><em>ne</em></big>'
header_links:
  - url: https://github.com/buildawesome-one
    title: <i class="fa-brands fa-github fa-lg"></i>
  - url: https://bsky.app/hashtag/BuildAwesome?author=any.digital
    title: <i class="fa-brands fa-bluesky"></i>
  - url: https://mastodon.social/@anydigital/tagged/BuildAwesome?boosts=1
    title: <i class="fa-brands fa-mastodon fa-lg"></i>
  - url: https://blades.ninja/
    title: <i class="dark-auto">🥷</i>
  - url: https://github.com/buildawesome-one/docs/tree/main/content
    title: <i class="fa-solid fa-laptop-code faded"></i>
footer_contents:
  - Code licensed [MIT](//github.com/buildawesome-one/kit/blob/main/LICENSE.md),
    docs [CC BY-SA 4.0](//github.com/buildawesome-one/docs/blob/main/content/LICENSE.md).
  - This site is powered by [Netlify](//www.netlify.com/) using <object data="/gh-content.svg" class="dark-auto"></object>
